spring.application.name=property

cloudinary.cloud_name=${daw600tbq}
cloudinary.api_key=${177478218558672}
cloudinary.api_secret=${pDjxAK8QPLwyABOhXdn8jWFKnbs}


# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/propertyat99
spring.datasource.username=root
spring.datasource.password=Gaurav@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration (if you are using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.address=0.0.0.0
server.port=8080


# AWS Configuration
aws.accessKeyId=${AKIARHQZYWXAHYKLJU7E}
aws.secretKey=${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}
aws.region={ap-south-1}
aws.s3.bucket=${youshell-images-2026}